-- Late Shift Save Game
return {
  currentVideo = "913398e931405382ff0e1d99870880b3",
  gameVars = {
    has_pepper_spray = false,
    know_about_party = false,
    key_given = false,
    cctv_seg = false,
    with_lee = false,
    may_likes_matt = false,
    respect_earned = false,
    sabotage = false,
    intervened = false,
    sold_for = 0,
    gone_upstairs = false,
    security_alert = false,
    blank_book = false,
    gone_to_woe = false,
    has_cookie = false,
    report_to_police = false,
    matt_escape = false,
    may_kiss = false,
    knife_long = false,
    matt_alone_playing = false,
    may_stabbed = false,
    cross_exam = false,
    turned_away = false,
    left_may_crying = false,
    go_home = false,
    beat_up = false,
  },
  language = "en",
  showSubtitles = true,
  showDebug = false
}
