cname[ 1] = { x= 8.460000000000001, y= 39.25,  z="Andromeda" }
cname[ 2] = { x= 151.77, y=-33.66,  z="Antlia" }
cname[ 3] = { x= 242.01, y=-76.42,  z="Apus" }
cname[ 4] = { x= 340.45, y=-10.53,  z="Aquarius" }
cname[ 5] = { x= 295.35, y= 3.37,  z="Aquila" }
cname[ 6] = { x= 258.46, y=-51.89,  z="Ara" }
cname[ 7] = { x= 40.14, y= 22.57,  z="Aries" }
cname[ 8] = { x= 89.2, y= 42.81,  z="Auriga" }
cname[ 9] = { x= 220.3, y= 32.33,  z="Bootes" }
cname[ 10] = { x= 70.81, y=-38.84,  z="Caelum" }
cname[ 11] = { x= 92.26000000000001, y= 71.95999999999999,  z="Camelopardalis" }
cname[ 12] = { x= 127.45, y= 23.56,  z="Cancer" }
cname[ 13] = { x= 195.3, y= 42.35,  z="Canes_Venatici" }
cname[ 14] = { x= 102.45, y=-22.69,  z="Canis_Major" }
cname[ 15] = { x= 114.36, y= 6.76,  z="Canis_Minor" }
cname[ 16] = { x= 315.72, y=-19.65,  z="Capricornus" }
cname[ 17] = { x= 116.41, y=-57.17,  z="Carina" }
cname[ 18] = { x= 13.05, y= 60.3,  z="Cassiopeia" }
cname[ 19] = { x= 194.25, y=-44,  z="Centaurus" }
cname[ 20] = { x= 336.25, y= 72.56,  z="Cepheus" }
cname[ 21] = { x= 25.63, y=-6.64,  z="Cetus" }
cname[ 22] = { x= 180, y=-81.98999999999999,  z="Chamaeleon" }
cname[ 23] = { x= 217.9, y=-67.7,  z="Circinus" }
cname[ 24] = { x= 85.56999999999999, y=-37.09,  z="Columba" }
cname[ 25] = { x= 191.22, y= 22.65,  z="Coma_Berenices" }
cname[ 26] = { x= 279.82, y=-41.25,  z="Corona_Australis" }
cname[ 27] = { x= 238.2, y= 32.63,  z="Corona_Borealis" }
cname[ 28] = { x= 185.8, y=-18.36,  z="Corvus" }
cname[ 29] = { x= 170.22, y=-13.25,  z="Crater" }
cname[ 30] = { x= 187.21, y=-60.7,  z="Crux" }
cname[ 31] = { x= 308.97, y= 49.58,  z="Cygnus" }
cname[ 32] = { x= 309.94, y= 12.1,  z="Delphinus" }
cname[ 33] = { x= 79.98999999999999, y=-63.99,  z="Dorado" }
cname[ 34] = { x= 269.17, y= 66.06,  z="Draco" }
cname[ 35] = { x= 318.76, y= 7.94,  z="Equuleus" }
cname[ 36] = { x= 58.14, y=-17.01,  z="Eridanus" }
cname[ 37] = { x= 41.49, y=-26.94,  z="Fornax" }
cname[ 38] = { x= 102.72, y= 24.82,  z="Gemini" }
cname[ 39] = { x= 336.85, y=-45.86,  z="Grus" }
cname[ 40] = { x= 261.37, y= 31.23,  z="Hercules" }
cname[ 41] = { x= 48.18, y=-52,  z="Horologium" }
cname[ 42] = { x= 137.04, y=-11.32,  z="Hydra" }
cname[ 43] = { x= 38.83, y=-72.08,  z="Hydrus" }
cname[ 44] = { x= 317.06, y=-52.68,  z="Indus" }
cname[ 45] = { x= 337.71, y= 46.67,  z="Lacerta" }
cname[ 46] = { x= 150, y= 7,  z="Leo" }
cname[ 47] = { x= 154.73, y= 33.24,  z="Leo_Minor" }
cname[ 48] = { x= 81.54000000000001, y=-19.35,  z="Lepus" }
cname[ 49] = { x= 227.8, y=-15.45,  z="Libra" }
cname[ 50] = { x= 230.64, y=-42.28,  z="Lupus" }
cname[ 51] = { x= 116.01, y= 47.83,  z="Lynx" }
cname[ 52] = { x= 283.62, y= 40.65,  z="Lyra" }
cname[ 53] = { x= 82.5, y=-79.98999999999999,  z="Mensa" }
cname[ 54] = { x= 314.13, y=-36.2,  z="Microscopium" }
cname[ 55] = { x= 104.43, y=-3.74,  z="Monoceros" }
cname[ 56] = { x= 186.9, y=-69.88,  z="Musca" }
cname[ 57] = { x= 240.62, y=-52.29,  z="Norma" }
cname[ 58] = { x= 332.59, y=-84.73,  z="Octans" }
cname[ 59] = { x= 255.55, y=-2.65,  z="Ophiuchus" }
cname[ 60] = { x= 83.48999999999999, y= 3.59,  z="Orion" }
cname[ 61] = { x= 287.4, y=-65.14,  z="Pavo" }
cname[ 62] = { x= 339.25, y= 19.65,  z="Pegasus" }
cname[ 63] = { x= 52.71, y= 44.89,  z="Perseus" }
cname[ 64] = { x= 10.98, y=-48.23,  z="Phoenix" }
cname[ 65] = { x= 80.70999999999999, y=-51.63,  z="Pictor" }
cname[ 66] = { x= 13.36, y= 15.48,  z="Pisces" }
cname[ 67] = { x= 336.15, y=-31.43,  z="Piscis_Austrinus" }
cname[ 68] = { x= 118.09, y=-32.39,  z="Puppis" }
cname[ 69] = { x= 133.36, y=-29.21,  z="Pyxis" }
cname[ 70] = { x= 58.48, y=-60.49,  z="Reticulum" }
cname[ 71] = { x= 295, y= 17,  z="Sagitta" }
cname[ 72] = { x= 290.77, y=-29.11,  z="Sagittarius" }
cname[ 73] = { x= 252.97, y=-35.67,  z="Scorpius" }
cname[ 74] = { x= 15, y=-38.5,  z="Sculptor" }
cname[ 75] = { x= 279.76, y=-10.11,  z="Scutum" }
cname[ 76] = { x= 235.96, y= 10.85,  z="Serpens_Caput" }
cname[ 77] = { x= 269.37, y=-13.52,  z="Serpens_Cauda" }
cname[ 78] = { x= 151.53, y=-1.87,  z="Sextans" }
cname[ 79] = { x= 61.42, y= 17.34,  z="Taurus" }
cname[ 80] = { x= 288.66, y=-51.54,  z="Telescopium" }
cname[ 81] = { x= 30.64, y= 32.34,  z="Triangulum" }
cname[ 82] = { x= 241.86, y=-65.90000000000001,  z="Triangulum_Australe" }
cname[ 83] = { x= 357.42, y=-64.06,  z="Tucana" }
cname[ 84] = { x= 153.94, y= 57.48,  z="Ursa_Major" }
cname[ 85] = { x= 224.61, y= 75.04000000000001,  z="Ursa_Minor" }
cname[ 86] = { x= 140.05, y=-48.51,  z="Vela" }
cname[ 87] = { x= 200.14, y=-3.49,  z="Virgo" }
cname[ 88] = { x= 114.88, y=-69.39,  z="Volans" }
cname[ 89] = { x= 305.5, y= 25.03,  z="Vulpecula" }
