local a = 0
local b = 0
local c = 0
local d = 0
local e = 0
local f = 0
local g = 0
local h = 0

while true do
a = a + 0
b = b + 0
c = c + 0
d = d + 0
e = e + 1
f = f + 0
g = g + 33
h = g + 33

if e>=0 and e<=9 then
file = io.open("1Devoutput.lua","a")
file:write("elseif currentTime >= ",g," and currentTime <= ",h ," then","\n")
file:write('frame1 = Image.load("harehare/vlcsnap-',a,b,c,d,e,'.png")',"\n")
file:write("screen:blit(0, 0, frame1, 0, 0, 0, 480, 272)","\n")
file:write("frame1:free()","\n")
file:close()
end

if e>=10 and e<=99 then
file = io.open("1Devoutput.lua","a")
file:write("elseif currentTime >= ",g," and currentTime <= ",h ," then","\n")
file:write('frame1 = Image.load("harehare/vlcsnap-',a,b,c,e,'.png")',"\n")
file:write("screen:blit(0, 0, frame1, 0, 0, 0, 480, 272)","\n")
file:write("frame1:free()","\n")
file:close()
end

if e>=100 and e<=999 then
file = io.open("1Devoutput.lua","a")
file:write("elseif currentTime >= ",g," and currentTime <= ",h ," then","\n")
file:write('frame1 = Image.load("harehare/vlcsnap-',a,b,e,'.png")',"\n")
file:write("screen:blit(0, 0, frame1, 0, 0, 0, 480, 272)","\n")
file:write("frame1:free()","\n")
file:close()
end

if e>=1000 and e<=65000 then
file = io.open("1Devoutput.lua","a")
file:write("elseif currentTime >= ",g," and currentTime <= ",h ," then","\n")
file:write('frame1 = Image.load("harehare/vlcsnap-',a,e,'.png")',"\n")
file:write("screen:blit(0, 0, frame1, 0, 0, 0, 480, 272)","\n")
file:write("frame1:free()","\n")
file:close()
end

end

-----------------------------
--www.lua.org/cgi-bin/demo

--local a = 0
--local b = 0
--local c = 0
--local d = 0
--local e = 0
--local f = 0
--while true do
--a = a + 0
--b = b + 0
--c = c + 0
--d = d + 0
--e = e + 1
--f = f + 0

--if e>=0 and e<=9 then
--io.write("a,b,c,d,e,"\n")
--elseif e>=9 and e<=99 then
--io.write(a,b,c,e,"\n")
--elseif e>=99 and e<=999 then
--io.write(a,b,e,"\n")
--elseif e>=999 and e<=9999 then
--io.write(a,e,"\n")
--end

--end





