if nexxchk == 0 and nexx == 3 then
file = io.open("./save/sdata.lua","a")
file:write("nexx = 3\nnexxchk = 1\n")
file:close()
nexxchk = 1
end	

if menuprompt == 1 and menupromtsv == 0 then
file = io.open("./save/sdata.lua","a")
file:write("menuprompt = 1\nmenupromtsv = 1\n")
file:close()
menupromtsv = 1
end	

if s1save == 0 and s1check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s1check = 1\ns1save = 1\n")
file:close()
s1save = 1
end	

if s2save == 0 and s2check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s2check = 1\ns2save = 1\n")
file:close()
s2save = 1
end	

if s3save == 0 and s3check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s3check = 1\ns3save = 1\n")
file:close()
s3save = 1
end	

if s4save == 0 and s4check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s4save = 1\ns4check = 1\n")
file:close()
s4save = 1
end	


if s5save == 0 and s5check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s5save = 1\ns5check = 1\n")
file:close()
s5save = 1
end	


if s6save == 0 and s6check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s6save = 1\ns6check = 1\n")
file:close()
s6save = 1
end	

if s7save == 0 and s7check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s7save = 1\ns7check = 1\n")
file:close()
s3save = 1
end	

if s8save == 0 and s8check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s8save = 1\ns8check = 1\n")
file:close()
s8save = 1
end	

if s9save == 0 and s9check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s9save = 1\ns9check = 1\n")
file:close()
s9save = 1
end	

if s10save == 0 and s10check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s10save = 1\ns10check = 1\n")
file:close()
s10save = 1
end	

if s11save == 0 and s11check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s11save = 1\ns11check = 1\n")
file:close()
s11save = 1
end	

if s12save == 0 and s12check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s12save = 1\ns12check = 1\n")
file:close()
s12save = 1
end	

if s13save == 0 and s13check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s13save = 1\ns13check = 1\n")
file:close()
s13save = 1
end	

if s14save == 0 and s14check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s14save = 1\ns14check = 1\n")
file:close()
s14save = 1
end	

if s15save == 0 and s15check == 1 then
file = io.open("./save/sdata.lua","a")
file:write("s15save = 1\ns15check = 1\n")
file:close()
s15save = 1
end	

if sg15notesv == 0 and sg15note == 1 then
file = io.open("./save/sdata.lua","a")
file:write("sg15notesv = 1\nsg15note = 1\n")
file:close()
sg15notesv = 1
end	

if endingsv == 0 and ending == 1 then
file = io.open("./save/sdata.lua","a")
file:write("endingsv = 1\nending = 1\n")
file:close()
endingsv = 1
end	








